### ISSUE TITLE
Set up the Kanban board

### ISSUE THREAD

**Issue by baqar-abbas** [baqar-abbas/recipe-app-capstone#11]
### 🌟Features:
> - [x] - The GitHub project's Kanban board is created from scratch.
> - [x] - Tasks are created based on project requirements with titles and complexity points.
> - [x] - Assignee's are designated fairly for each task.
> - [x] - All cards now have assignee's with balanced workloads.

### 📃 Group Members:
> - [Baqar Abbas ](https://github.com/baqar-abbas)
> - [Abdul Ali Noori](https://github.com/ab-noori)

### 🔗 Link to Kanban board setup 

> - https://github.com/users/baqar-abbas/projects/5/views/1?layout=board

**Comment by divinecharlotte** [comment]
Hi @Team      , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- kanban board👍 
- Implemented some project requirements   👍 

 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

- [x] Kindly consider making sure each requirement has at least one corresponding card in the Kanban board cause some requirements are missing in your Kanban board kindly do so to make sure that no requirement will be skipped unexpectedly

_Check the comments under the review._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by julie-ify** [comment]
@ab-noori avoid editing the content of the reviews. If you wish to comment simply add your comment to the issues thread but leave the reviewer's message as it was. It is important to follow the thread of communication.

**Comment by julie-ify** [comment]
Hi @baqar-abbas and @ab-noori,

Good job so far!

## Highlights!
- Descriptive issue ✔️ 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
- [ ] You are missing the General Shopping list task from the project requirement.

- [ ] This [Authentication task](https://github.com/baqar-abbas/recipe-app-capstone/issues/9) is the same as this [Login and registration task](https://github.com/baqar-abbas/recipe-app-capstone/issues/1). Kindly remove one.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by baqar-abbas** [comment]
Suggested changes by the code reviewer have been implemented. sending it for a review again.

**Comment by baqar-abbas** [comment]
Added the card for General Shopping List and removed the card of authentication as suggested by the code reviewer.

**Comment by mckent05** [comment]
Hi @divinecharlotte, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to start your capstone :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All cards have been fairly assigned ✔️ ✔️ 
- Your Kanban board has been properly created 👏 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ab-noori** [comment]
> @ab-noori avoid editing the content of the reviews. If you wish to comment simply add your comment to the issues thread but leave the reviewer's message as it was. It is important to follow the thread of communication.

Hi @julie-ify,
Thanks for mentioning.
It was mistakenly removed, I just wanted to give her a reply.

**Comment by ab-noori** [comment]
Hi @mckent05 👋,
Thank you so much 🙏 for reviewing and approving our project.
